[package]
name = "zeps-core"
version = "0.1.0"
authors = ["The zDevelopers"]

[dependencies]
serde = "1.0.8"
serde_json = "1.0.2"
serde_derive = "1.0.8"
failure = "0.1.1"
failure_derive = "0.1.1"

[lib]
name = "zeps"
path = "src/lib.rs"

[[bin]]
name = "zeps-core"
path = "src/main.rs"
